"""Add account type

Revision ID: 3959cd6411bf
Revises: ff7fa3904311
Create Date: 2026-01-03 22:08:30.413621

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3959cd6411bf"
down_revision: Union[str, Sequence[str], None] = "ff7fa3904311"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    account_type_enum = sa.Enum("ADMIN", "DEFAULT", name="accounttype")
    account_type_enum.create(op.get_bind())

    op.drop_index(op.f("ix_mail_cache_external_id"), table_name="mail_cache")
    op.drop_index(op.f("ix_mail_cache_state"), table_name="mail_cache")
    op.drop_table("mail_cache")
    op.add_column(
        "account",
        sa.Column(
            "account_type", sa.Enum("ADMIN", "DEFAULT", name="accounttype"), nullable=False, server_default="DEFAULT"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "account_type")
    op.create_table(
        "mail_cache",
        sa.Column("time_received", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("sender", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("recipient", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("subject", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "state",
            postgresql.ENUM("RECEIVED", "PROCESSED", "FAILED", name="mailstate"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("external_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("body", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("raw_email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("job_results", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("errors", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("mail_cache_pkey")),
    )
    op.create_index(op.f("ix_mail_cache_state"), "mail_cache", ["state"], unique=False)
    op.create_index(op.f("ix_mail_cache_external_id"), "mail_cache", ["external_id"], unique=False)
    # ### end Alembic commands ###
