"""Initial

Revision ID: cf29a8d15c0e
Revises:
Create Date: 2026-01-02 16:49:03.774655

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf29a8d15c0e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("info", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_name"), "account", ["name"], unique=True)
    op.create_table(
        "sender",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mail_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("info", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sender_mail_address"), "sender", ["mail_address"], unique=True)
    op.create_index(op.f("ix_sender_name"), "sender", ["name"], unique=True)
    op.create_table(
        "mail",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("time_received", sa.Integer(), nullable=False),
        sa.Column("sender", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("recipient", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("subject", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("state", sa.Enum("RECEIVED", "PROCESSED", "FAILED", name="mailstate"), nullable=False),
        sa.Column("body_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("raw_email_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("job_results", sa.JSON(), nullable=True),
        sa.Column("errors", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sender"],
            ["sender.mail_address"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mail_sender"), "mail", ["sender"], unique=False)
    op.create_index(op.f("ix_mail_state"), "mail", ["state"], unique=False)
    op.create_table(
        "sender_account_link",
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["sender.id"],
        ),
        sa.PrimaryKeyConstraint("sender_id", "account_id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("info", sa.Text(), nullable=True),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_table("user")
    op.drop_table("sender_account_link")
    op.drop_index(op.f("ix_mail_state"), table_name="mail")
    op.drop_index(op.f("ix_mail_sender"), table_name="mail")
    op.drop_table("mail")
    op.drop_index(op.f("ix_sender_name"), table_name="sender")
    op.drop_index(op.f("ix_sender_mail_address"), table_name="sender")
    op.drop_table("sender")
    op.drop_index(op.f("ix_account_name"), table_name="account")
    op.drop_table("account")
    # ### end Alembic commands ###
