"""remove_sender_fkey

Revision ID: ff7fa3904311
Revises: cf29a8d15c0e
Create Date: 2026-01-02 17:02:56.435677

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff7fa3904311"
down_revision: Union[str, Sequence[str], None] = "cf29a8d15c0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mail_sender"), table_name="mail")
    op.drop_constraint(op.f("mail_sender_fkey"), "mail", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f("mail_sender_fkey"), "mail", "sender", ["sender"], ["mail_address"])
    op.create_index(op.f("ix_mail_sender"), "mail", ["sender"], unique=False)
    # ### end Alembic commands ###
